### ISSUE TITLE
use of deprecated associated function `solana_sdk::pubkey::Pubkey::new`: 

### ISSUE THREAD

**Issue by Lusitaniae** [rpcpool/solana-accountsdb-sqs#62]
`use of deprecated associated function `solana_sdk::pubkey::Pubkey::new`: Please use 'Pubkey::from' or 'Pubkey::try_from' instead`

**Comment by fanatid** [comment]
Resolved in https://github.com/rpcpool/solana-accountsdb-sqs/commit/4cf34a37f13a17554b91a42cfc77ec2f0d22bf8e
